config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :relations

  resources :groups do
    get "add_book", on: :member
  end

  resources :groupings

  resources :books do
    get "add_author", on: :member
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  resources :users

  resources :clients

  resources :client_has_books

  root to: "books_catalog#index"

end

app/models/author.rb
class Author < ApplicationRecord

  has_many :relations
  has_many :books, through: :relations
  validates :name, presence: true
  validates :name, uniqueness: true

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:index, :new, :edit, :create, :update, :destroy]
  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully deleted.' }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/views/authors/_form.html.erb
<%= simple_form_for @author do |form| %>

  <%= form.input :name %>

  <%= form.submit %>

<% end %>

app/views/authors/destroy.js.erb
$('p:contains("Author was successfully created.")').remove();
$('p:contains("Author was successfully deleted.")').remove();
$('tr#<%= @author.id %>>').fadeOut(500, function(){
    $(this).remove();
});
$('header').after('<p class="alert alert-success">Author was successfully deleted.</p>');

app/views/authors/edit.html.erb
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-6">
    <h1>Editing Author</h1>
    <%= render 'form', author: @author %>
    <%= link_to 'Show', @author %> |
    <%= link_to 'Back', authors_path %>
  </div>
</div>

app/views/authors/index.html.erb
<% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<div class="col-sm-10">
  <h1>Authors</h1>
  <%= link_to 'New Author', new_author_path, class: "btn btn-info", id:"img" %>
  <table class="table">
    <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @authors.each do |author| %>
      <tr id="<%= author.id %>">
        <td><%= author.id %></td>
        <td><%= link_to author.name, author %></td>
        <td> <%= author.created_at.strftime("%d-%m-%Y") %> </td>
        <td> <%= author.updated_at.strftime("%d-%m-%Y") %> </td>
        <td>
          <%= link_to 'Show', author, class: "btn btn-success" %> |
          <%= link_to 'Edit', edit_author_path(author), class: "btn btn-warning" %> |
          <%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/authors/new.html.erb
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-6">
    <h1>New Author</h1>
    <%= render 'form', author: @author %>
    <%= link_to 'Back', authors_path %>
  </div>
</div>

app/views/authors/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<div class="row">
  <div class="col-sm-10">
    <h2><%= @author.name %></h2>
    <% unless @author.books.empty? %>
      <h3>
        List of books:
      </h3>
      <div class="row">
        <% @author.books.each do |book| %>
          <div class="col-sm-3">
            <%= image_tag book.image_url, id: "image_show" %>
            <h4><%= link_to book.title, book %></h4>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user && current_user.admin? %>
    <div class="col-sm-2" id="img">
      <%= link_to 'Edit', edit_author_path(@author), class: "btn btn-warning" %> |
      <%= link_to 'Back', authors_path, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>