config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :relations

  resources :groups do
    get "add_book", on: :member
  end

  resources :groupings

  resources :books do
    get "add_author", on: :member
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  resources :users

  resources :clients

  resources :client_has_books

  root to: "books_catalog#index"

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :groupings
  has_many :books, through: :groupings

  validates :name, presence: true
  validates :name, uniqueness: true

  def add_book(id)
    @book = Book.find(id)
    self.books << @book
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_book]
  before_action :require_admin, only: [:index, :new, :edit, :create, :update, :destroy]
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @groups = Group.all
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @books = Book.all
    @book_ids = @group.books.ids
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully deleted.' }
      format.js
    end
  end

  def add_book
    @group.add_book(params[:book_id])
    redirect_to edit_group_path(@group)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/views/groups/_form.html.erb
<%= simple_form_for @group do |form| %>

  <%= form.input :name %>

  <%= form.submit %>

<% end %>

app/views/groups/destroy.js.erb
$('p:contains("Group was successfully created.")').remove();
$('p:contains("Group was successfully deleted.")').remove();
$('tr#<%= @group.id %>>').fadeOut(500, function(){
    $(this).remove();
});
$('header').after('<p class="alert alert-success">Group was successfully deleted.</p>');

app/views/groups/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Editing Group</h1>
    <%= render 'form', group: @group %>
    <%= link_to 'Show', @group %> |
    <%= link_to 'Back', groups_path %>
  </div>
  <% if @books %>
    <div class="col-sm-3">
      <h3>Add books</h3>
      <table class="table">

        <% @books.each do |book| %>
          <% next if @book_ids.include? book.id %>
          <tr>
            <td><%= link_to book.title, book %></td>
            <td><%= link_to "Add", add_book_group_path(@group, book_id: book.id), class: "btn btn-warning btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
  <% unless @group.books.empty? %>
    <div class="col-sm-3">
      <h3>Delete books</h3>
      <table class="table">
        <% @group.books.each do |book| %>
          <tr>
            <td><%= link_to book.title, book %></td>
            <td><%= link_to "Delete", @group.groupings.find_by(book_id: book.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>
</div>

app/views/groups/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<div class="row">
  <div class="col-sm-10">
    <h1>Groups</h1>
    <% if current_user && current_user.admin? %>
      <%= link_to 'New Group', new_group_path, class: "btn btn-info", id:"img "%>
    <% end %>
    <table class="table">
      <thead>
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @groups.each do |group| %>
        <tr id="<%= group.id %>">
          <td> <%= group.id %> </td>
          <td> <%= link_to group.name, group %> </td>
          <td> <%= group.created_at.strftime("%d-%m-%Y") %> </td>
          <td> <%= group.updated_at.strftime("%d-%m-%Y") %> </td>
          <td>
            <%= link_to 'Show', group, class: "btn btn-success" %>
            <% if current_user && current_user.admin? %>|
              <%= link_to 'Edit', edit_group_path(group), class: "btn btn-warning" %> |
              <%= link_to 'Delete', group, method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/groups/new.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>New Group</h1>

    <%= render 'form', group: @group %>

    <%= link_to 'Back', groups_path %>
  </div>
  <div class="col-sm-3">
  </div>
</div>

app/views/groups/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<div class="row">
  <div class="col-sm-3">
    <h1>Groups</h1>
    <p class="lead">
      <%= link_to "All books", root_path %>
    </p>
    <% @groups.each do |group| %>
      <p class="lead">
        <%= link_to group.name, group %>
      </p>
    <% end %>
  </div>
  <div class="col-sm-9">
    <h1>
      <%= @group.name.capitalize %> group
      <% if current_user && current_user.admin? %>
        <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-warning" %>
      <% end %>
    </h1>
    <% unless @group.books.empty? %>
      <table class="table">
        <% @group.books.each do |book| %>
          <tr class="row">
            <td class="col-sm-2">
              <%= link_to book do %>
                <%= image_tag book.image_url, id: "img_catalog" %>
              <% end %>
            </td>
            <td class="col-sm">
              <p class="lead"><%= link_to book.title, book %></p>
              <p class="mb-0"><%= book.description %></p>
              <p class="lead">ID: <%= book.id %> | Count: <%= book.count %></p>
              <% if current_user && current_user.admin? %>
                <p class="lead">Reading now: <%= book.reading_now %></p>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
</div>