config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :relations

  resources :groups do
    get "add_book", on: :member
  end

  resources :groupings

  resources :books do
    get "add_author", on: :member
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  resources :users

  resources :clients

  resources :client_has_books

  root to: "books_catalog#index"

end

app/models/book.rb
class Book < ApplicationRecord

  after_initialize :set_default_for_reading_now

  validates :title, :image_url, :count, presence: true
  validates :title, uniqueness: true

  has_many :groupings
  has_many :groups, through: :groupings

  has_many :client_has_books, dependent: :destroy
  has_many :clients, through: :client_has_books

  has_many :relations
  has_many :authors, through: :relations

  def author_list
    self.authors.collect do |author|
      author.name
    end.join(", ")
  end

  def author_list=(authors_string)
    author_names = authors_string.split(",").collect{ |s| s.strip }.uniq
    new_or_found_authors = author_names.collect { |name| Author.find_or_create_by( name: name ) }
    self.authors = new_or_found_authors
  end

  def add_author(id)
    @author = Author.find(id)
    self.authors << @author
  end

  def clients_can_read
    Client.all - clients
  end

  def client_added
    update(count: self.count - 1, reading_now: self.reading_now + 1)
  end

  def client_destroyed
    update(count: self.count + 1, reading_now: self.reading_now - 1)
  end

  private

  def set_default_for_reading_now
    self.reading_now ||= 0
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :add_author]
  before_action :require_admin, only: [:index, :new, :edit, :create, :update, :destroy]
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @clients = Client.all
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    @authors = Author.all
    @author_ids = @book.authors.ids
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully deleted.' }
      format.js
    end
  end

  def add_author
    @book.add_author(params[:author_id])
    redirect_to edit_book_path(@book)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :count,  :description, :image_url, :author_list)
    end

end

app/views/books/_form.html.erb
<%= simple_form_for @book do |form| %>

  <%= form.input :title %>
  <%= form.input :description, input_html: {rows: 10} %>
  <%= form.input :count %>
  <%= form.input :image_url %>
  <%= form.input :author_list %>
  <%= form.submit %>

<% end %>

app/views/books/destroy.js.erb
$('p:contains("Book was successfully created.")').remove();
$('p:contains("Book was successfully deleted.")').remove();
$('tr#<%= @book.id %>>').fadeOut(500, function(){
    $(this).remove();
});
$('header').after('<p class="alert alert-success">Book was successfully deleted.</p>');

app/views/books/edit.html.erb
<div class="row">

  <div class="col-sm-6">
    <h1>Editing Book</h1>
    <%= render 'form', book: @book %>

    <%= link_to 'Show', @book %> |
    <%= link_to 'Back', books_path %>
  </div>

  <% if @authors.present? %>
    <div class="col-sm-3">
      <h2>Add authors</h2>
      <table class="table">

        <% @authors.each do |author| %>
          <% next if @author_ids.include? author.id %>
          <tr>
            <td><%= link_to author.name, author %></td>
            <td><%= link_to "Add", add_author_book_path(@book, author_id: author.id), class: "btn btn-warning btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
  <% end %>

  <% unless @book.authors.empty? %>
    <div class="col-sm-3">
      <h2>Delete authors</h2>
      <table class="table">
        <% @book.authors.each do |author| %>
        <tr class="authors">
          <td><%= link_to author.name, author %></td>
          <td><%= link_to "Remove", author.relations.find_by(book_id: @book.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
        </tr>
        <% end %>
      </table>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>

<h1>Books</h1>
<% if current_user && current_user.admin? %>
  <h3><%= link_to 'New Book', new_book_path, class: "btn btn-info", id: "img" %></h3>
<% end %>
<table class="table">
  <thead>
  <tr>
    <th>Image</th>
    <th>ID</th>
    <th>Title</th>
    <th>Count</th>
    <th>Reading Now</th>
    <th>Created at</th>
    <th>Updated at</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr id="<%= book.id %>">
      <td> <%= image_tag book.image_url, id: "table_image" %> </td>
      <td> <%= book.id %> </td>
      <td> <%= link_to book.title, book %> </td>
      <td> <%= book.count %> </td>
      <td> <%= book.reading_now %> </td>
      <td> <%= book.created_at.strftime("%d-%m-%Y") %> </td>
      <td> <%= book.updated_at.strftime("%d-%m-%Y") %> </td>
      <td>
        <%= link_to 'Show', book, class: "btn btn-success" %> |
        <%= link_to 'Edit', edit_book_path(book), class: "btn btn-warning" %> |
        <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger", remote: true %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<div class="row">
  <div class="col-sm-3">
  </div>
  <div class="col-sm-6">
    <h1>New Book</h1>

    <%= render 'form', book: @book %> <br/>

  </div>
</div>

app/views/books/show.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<div class="row">
  <div class="col-sm-5">
    <h1> <%= @book.title %> </h1>
    <% unless @book.authors.empty? %>
      <p class="lead">
        Authors:
        <% @book.authors.each do |author| %>
          <%= link_to author.name, author_path(author) %>
        <% end %>
      </p>
    <% end %>

    <% unless @book.groups.empty? %>
      <p class="lead">
        Groups:
        <% @book.groups.each do |group| %>
          <%= link_to group.name, group_path(group) %>
        <% end %>
      </p>
    <% end %>

    <p class="lead">
      <strong>Description:</strong>
      <%= @book.description %>
    </p>

    <% if current_user && current_user.admin? && @book.clients.any? %>
      <br/><h4>Clients Reading now:</h4>
      <table class="table">
        <% @book.clients.each do |client| %>
          <tr>
            <td><%= link_to "#{client.first_name} #{client.last_name}", client %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
    <br/>
  </div>
  <div class="col-sm-3">
    <%= image_tag @book.image_url, id: "img" %>
    <h2 class="lead">
      <p class="lead">ID: <%= @book.id %> | Count: <%= @book.count %></p>
      <% if current_user && current_user.admin? %>
        <p class="lead">Reading now: <%= @book.reading_now %></p>
      <% end %>
    </h2>
  </div>
  <% if current_user && current_user.admin? %>
    <div class="col-sm-4" id="img">
      <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-warning" %> |
      <%= link_to 'Back', books_path, class: "btn btn-danger" %>
    </div>
    <% if @book.clients_can_read.any? && @book.count > 0 %>
      <div class="row">
        <div class="col-sm-4">
          <h3>Give books</h3>
          <table class="table">
            <% @book.clients_can_read.each do |client| %>
              <tr>
                <td><%= link_to "#{client.first_name} #{client.last_name}", client %></td>
                <td><%= link_to "Give Book", client_has_books_path(client_id: client.id, book_id: @book.id), method: :post, class: "btn btn-primary btn-sm" %></td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    <% end %>
  <% end %>
</div>