config/routes.rb
Rails.application.routes.draw do

  resources :authors
  resources :relations

  resources :groups do
    get "add_book", on: :member
  end

  resources :groupings

  resources :books do
    get "add_author", on: :member
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'

  resources :users

  resources :clients

  resources :client_has_books

  root to: "books_catalog#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book's Library</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
          <div class="container-fluid">
            <div class="col-sm-9">
              <div class="navbar-header">
                <%= link_to "Book's Library", root_path, class: "navbar-brand" %>
              </div>
              <ul class="nav navbar-nav">
                <li class="nav-link"><%= link_to "Catalog", root_path, class: "nav-link" %></li>
              </ul>
              <% if current_user && current_user.admin? %>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Books", books_url, class: "nav-link" %></li>
                </ul>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Groups", groups_url %></li>
                </ul>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Authors", authors_url %></li>
                </ul>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Admins", users_url %></li>
                </ul>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Clients", clients_url %></li>
                </ul>
                <ul class="nav navbar-nav">
                  <li class="nav-link"><%= link_to "Reading Now Books", client_has_books_url %></li>
                </ul>
              <% end %>
            </div>

            <div class="col-sm-3 session_bar">
              <% if current_user %>
                <strong style="color: antiquewhite; margin-right: 15px;"><%= current_user.login %></strong>
                <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-primary btn-sm" %>
              <% else %>
                <%= link_to "Log in", login_path, class: "btn btn-primary" %> |
                <%= link_to "Sign up", signup_path, class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </nav>

      </header>
      <%= yield %>
    </div>
  </body>
</html>